version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-browser-legacy
        auth:
          username: vinniiee
          password: $DOCKER_PASSWORD

    working_directory: ~/repo

    environment:
      MAVEN_OPTS:-Xmx3200m
      DOCKER_PASSWORD: Qwerty@12345

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
            - v1-dependencies- # fallback in case previous cache key is not found
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn integration-test