version: 2.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.12-browsers


    working_directory: ~/repo

    environment:
      MAVEN_OPTS:-Xmx3200m


    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
            - v1-dependencies- # fallback in case previous cache key is not found
      - run: mvn dependency:go-offline
#      - run: git config user.email "vs28245@gmail.com"
#      - run: git config user.name "via CircleCI build"
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn --batch-mode release:prepare release:perform -s .circleci/settings.xml